use {
    clap::{App, Arg, ArgMatches},
    indoc::indoc,
    solana_adversary::block_generator_config::{
        BlockGeneratorAccountsSource, BlockGeneratorConfig,
    },
    std::path::PathBuf,
};

fn generate_blocks_with_accounts_arg<'a, 'b>() -> Arg<'a, 'b> {
    Arg::with_name("generate_blocks_with_accounts")
        .long("generate-blocks-with-accounts")
        .takes_value(true)
        .value_name("PATH")
        .hidden(false)
        .help("when leader, generate transactions in banking stage")
        .long_help(indoc! {"
            When running as a leader, generate transactions in banking stage using a predefined list
            of attack generators, instead of just receiving transactions over the network.
            Argument is a configuration file generated by
                https://github.com/solana-labs/account-configure-tool
            List of attacks is in
                core::banking_stage::adversary::\\
                transaction_generators::ActiveGenerator::create_generator()
        "})
}

pub trait BankingStageArgs {
    fn banking_stage_args(self) -> Self;
}

impl BankingStageArgs for App<'_, '_> {
    fn banking_stage_args(self) -> Self {
        self.arg(generate_blocks_with_accounts_arg())
    }
}

pub fn initialize_validator_config(
    block_generator_config: &mut Option<BlockGeneratorConfig>,
    matches: &ArgMatches<'_>,
) {
    let accounts = matches
        .value_of("generate_blocks_with_accounts")
        .map(|path| BlockGeneratorAccountsSource::AccountsPath(PathBuf::from(path)));

    if let Some(accounts) = accounts {
        *block_generator_config = Some(BlockGeneratorConfig { accounts });
    }
}
