//! Hotpath for batches of guaranteed failed transactions to be recorded/committed without
//! loading or execution. Fee-paying is still necessary, so only the fee-paying account will
//! be loaded and committed for each transaction.

use {
    crate::banking_stage::{
        committer::{CommitTransactionDetails, Committer},
        consumer::{
            ExecuteAndCommitTransactionsOutput, LeaderProcessedTransactionCounts,
            ProcessTransactionBatchOutput,
        },
        leader_slot_timing_metrics::LeaderExecuteAndCommitTimings,
        qos_service::QosService,
        scheduler_messages::MaxAge,
    },
    itertools::{izip, Itertools},
    solana_account::WritableAccount,
    solana_clock::MAX_PROCESSING_AGE,
    solana_instruction::error::InstructionError,
    solana_measure::measure_us,
    solana_poh::transaction_recorder::{
        RecordTransactionsSummary, RecordTransactionsTimings, TransactionRecorder,
    },
    solana_program_runtime::execution_budget::SVMTransactionExecutionAndFeeBudgetLimits,
    solana_runtime::{
        bank::{Bank, LoadAndExecuteTransactionsOutput, ProcessedTransactionCounts},
        transaction_batch::TransactionBatch,
    },
    solana_runtime_transaction::transaction_with_meta::TransactionWithMeta,
    solana_svm::{
        account_loader::LoadedTransaction,
        transaction_balances::BalanceCollector,
        transaction_error_metrics::TransactionErrorMetrics,
        transaction_execution_result::{ExecutedTransaction, TransactionExecutionDetails},
        transaction_processing_result::{
            ProcessedTransaction, TransactionProcessingResultExtensions,
        },
    },
    solana_svm_timings::{ExecuteTimingType, ExecuteTimings},
    solana_transaction_error::TransactionError,
    std::{collections::HashMap, num::Saturating},
};

/// Simplified recording and committing without execution. Will only work correctly for
/// transactions that are guaranteed to fail.
///
/// This function will still run through QoS to ensure we keep within block limits.
///
/// See `banking_stage::consumer::Consumer::process_and_record_aged_transactions()`, and
/// `process_and_record_transactions_with_pre_results()` in the same module, for reference.
pub fn process_and_record_aged_transactions(
    qos_service: &QosService,
    transaction_recorder: &TransactionRecorder,
    committer: &Committer,
    bank: &Bank,
    transactions: &[impl TransactionWithMeta],
    _max_ages: &[MaxAge],
) -> ProcessTransactionBatchOutput {
    // `Consumer::process_and_record_aged_transactions()` is verifying transactions against the
    // `max_ages` here.  This is due to the fact, that transactions are pre-verified when they are
    // received.  And a considerable amount of time might have passed since that point and when they
    // are processed here.
    //
    // But in case of the failed transaction hotpath, all of transactions are generated by the
    // internal generators, we do not expect them to fail the age validation.  This could actually
    // fail in certain edge cases, probably causing cluster divergence.

    let ((transaction_qos_cost_results, cost_model_throttled_transactions_count), cost_model_us) =
        measure_us!(qos_service.select_and_accumulate_transaction_costs(
            bank,
            transactions,
            // `Consumer::process_and_record_aged_transactions()` passes the `max_age` check results
            // here, but we assume all transaction pass it.
            std::iter::repeat(Ok(())),
        ));

    // Only lock accounts for those transactions are selected for the block;
    // Once accounts are locked, other threads cannot encode transactions that will modify the
    // same account state
    //
    // Transaction generators are producing explicit worker thread indices for all transactions, and
    // thus should avoid overlaps, making locking unnecessary.  But, in practice, this may still
    // fail, as the generators are racing against each other, and certain patterns, or bugs, could
    // produce overlaps.  As this verification is supposed to be fast, and the call is constructing
    // a `TransactionBatch` instance that we need later, we keep this call as is.
    let (batch, lock_us) = measure_us!(bank.prepare_sanitized_batch_with_results(
        transactions,
        transaction_qos_cost_results.iter().map(|r| match r {
            Ok(_cost) => Ok(()),
            Err(err) => Err(err.clone()),
        })
    ));

    let execute_and_commit_transactions_output =
        execute_and_commit_failed_transactions(transaction_recorder, committer, bank, &batch);

    // Once the accounts are new transactions can enter the pipeline to process them
    let (_, unlock_us) = measure_us!(drop(batch));

    // We do not want the `QosService` to actually update the execution costs, as they would be
    // incorrect in our case.  We we skip loading of the accounts, the CUs we estimated will be
    // below the correct ones, produced during an actual execution, allowing the leader to pack more
    // transactions into the block than what a replay stage will.
    //
    // Instead we go the opposite route.  `QosService::select_and_accumulate_transaction_costs()`
    // has already added the full CU estimate from the transaction, and
    // `QosService::remove_or_update_costs()` is supposed to refund the CUs that were not used.
    //
    // By skipping the refund, we make sure the leader is more conservative than the replay,
    // producing under-packed blocks.  But as these failed transactions are generally attacking some
    // resource sensitive parts of the system, it is unlikely we really need to pack a full block
    // to produce a desired effect.
    //
    // We still need to reduce the in flight transaction counter, which is normally called inside of
    // the `QosService::remove_or_update_costs()` call.
    //
    // QosService::remove_or_update_costs(
    //     transaction_qos_cost_results.iter(),
    //     execute_and_commit_transactions_output
    //         .commit_transactions_result
    //         .as_ref()
    //         .ok(),
    //     bank,
    // );
    {
        // This is what `QosService::remove_or_update_recorded_transaction_costs()` does.
        let mut cost_tracker = bank.write_cost_tracker().unwrap();
        cost_tracker.sub_transactions_in_flight(
            transaction_qos_cost_results
                .iter()
                .filter(|&res| res.is_ok())
                .count(),
        );
    }

    // Computing accurate CUs without execution is non-trivial.  And as it is only needed for
    // metrics, we skip this step here.
    //
    // let (cu, us) =
    //     Self::accumulate_execute_units_and_time(&execute_and_commit_timings.execute_timings);
    // self.qos_service.accumulate_actual_execute_cu(cu);
    // self.qos_service.accumulate_actual_execute_time(us);

    qos_service.report_metrics(bank.slot());

    debug!(
        "failed_transaction_hotpath: {} lock: {}us unlock: {}us txs_len: {}",
        bank.slot(),
        lock_us,
        unlock_us,
        transactions.len(),
    );

    ProcessTransactionBatchOutput {
        cost_model_throttled_transactions_count,
        cost_model_us,
        execute_and_commit_transactions_output,
    }
}

/// Roughly matches the functionality of the
/// `Consumer::execute_and_commit_transactions_locked()`.  We avoid the actual execution of these
/// transactions, mostly just the commit part is here.
fn execute_and_commit_failed_transactions(
    transaction_recorder: &TransactionRecorder,
    committer: &Committer,
    bank: &Bank,
    batch: &TransactionBatch<impl TransactionWithMeta>,
) -> ExecuteAndCommitTransactionsOutput {
    let mut execute_and_commit_timings = LeaderExecuteAndCommitTimings::default();

    // `Consumer::execute_and_commit_transactions_locked()` will collect balances here for any
    // tokens invoked in the transaction.  This causes the token accounts and the mint accounts to
    // be loaded.  Which we want to avoid for the hotpath in the first place.
    //
    // So we are going to skip the balance updates.  They are relevant for certain RPC requests.
    // But considering we know that all the transactions are going to fail, we may only have
    // incorrect balances for the transaction payer accounts, as a result, if at all.

    let min_max = batch
        .sanitized_transactions()
        .iter()
        .filter_map(|transaction| {
            transaction
                .compute_budget_instruction_details()
                .sanitize_and_convert_to_compute_budget_limits(&bank.feature_set)
                .ok()
                .map(|limits| limits.compute_unit_price)
        })
        .minmax();
    let (min_prioritization_fees, max_prioritization_fees) =
        min_max.into_option().unwrap_or_default();

    let mut error_counters = TransactionErrorMetrics::default();
    // For the moment, failed transaction hotpath logic assumes that all the passed transactions
    // are going to fail the compute budget limits.
    //
    // It is important for the transaction to actually do that.
    //
    // TODO It would be great to actually have a check here, that would verify that the first
    // transaction instruction is a `ComputeBudgetInstruction::set_compute_unit_limit()`
    // instruction.  We should probably also check the argument and make sure it is at or below
    // a certain known small value.  For the write program attack we are using 25_000, so maybe
    // it is a good limit?

    // `execute_and_commit_transactions_locked()` invokes
    // `bank.load_and_execute_transactions_output()` here, but we just assume we know the
    // loading and the execution results already.
    let (load_and_execute_transactions_output, load_execute_us) =
        measure_us!(load_and_execute_failed_transaction(
            bank,
            batch,
            MAX_PROCESSING_AGE,
            &mut execute_and_commit_timings.execute_timings,
            &mut error_counters
        ));
    let LoadAndExecuteTransactionsOutput {
        processing_results,
        processed_counts,
        balance_collector,
    } = load_and_execute_transactions_output;
    execute_and_commit_timings.load_execute_us = load_execute_us;

    let transaction_counts = LeaderProcessedTransactionCounts {
        processed_count: processed_counts.processed_transactions_count,
        processed_with_successful_result_count: processed_counts
            .processed_with_successful_result_count,
        attempted_processing_count: processing_results.len() as u64,
    };

    let (processed_transactions, processing_results_to_transactions_us) =
        measure_us!(processing_results
            .iter()
            .zip(batch.sanitized_transactions())
            .filter_map(|(processing_result, tx)| {
                if processing_result.was_processed() {
                    Some(tx.to_versioned_transaction())
                } else {
                    None
                }
            })
            .collect_vec());

    let (freeze_lock, freeze_lock_us) = measure_us!(bank.freeze_lock());
    execute_and_commit_timings.freeze_lock_us = freeze_lock_us;

    let (record_transactions_summary, record_us) =
        measure_us!(transaction_recorder.record_transactions(bank.slot(), processed_transactions));
    execute_and_commit_timings.record_us = record_us;

    let RecordTransactionsSummary {
        result: record_transactions_result,
        record_transactions_timings,
        starting_transaction_index,
    } = record_transactions_summary;
    execute_and_commit_timings.record_transactions_timings = RecordTransactionsTimings {
        processing_results_to_transactions_us: Saturating(processing_results_to_transactions_us),
        ..record_transactions_timings
    };

    if let Err(recorder_err) = record_transactions_result {
        // Unlike `execute_and_commit_transactions_locked()` we are not going to retry any of
        // these transactions, as we assume it is the generator fault for them to fail in the
        // first place.
        return ExecuteAndCommitTransactionsOutput {
            transaction_counts,
            retryable_transaction_indexes: vec![],
            commit_transactions_result: Err(recorder_err),
            execute_and_commit_timings,
            error_counters,
            min_prioritization_fees,
            max_prioritization_fees,
        };
    }

    let (commit_time_us, commit_transaction_statuses) =
        if processed_counts.processed_transactions_count != 0 {
            committer.commit_transactions(
                batch,
                processing_results,
                starting_transaction_index,
                bank,
                balance_collector,
                &mut execute_and_commit_timings,
                &processed_counts,
            )
        } else {
            (
                0,
                vec![
                    CommitTransactionDetails::NotCommitted(TransactionError::CommitCancelled);
                    processing_results.len()
                ],
            )
        };

    drop(freeze_lock);

    debug!(
        "failed_transaction_hotpath: {} execute_and_commit_failed_transactions: {}us record: {}us \
         commit: {}us txs_len: {}",
        bank.slot(),
        load_execute_us,
        record_us,
        commit_time_us,
        batch.sanitized_transactions().len(),
    );

    ExecuteAndCommitTransactionsOutput {
        transaction_counts,
        retryable_transaction_indexes: vec![],
        commit_transactions_result: Ok(commit_transaction_statuses),
        execute_and_commit_timings,
        error_counters,
        min_prioritization_fees,
        max_prioritization_fees,
    }
}

// This is a replacement for `bank.load_and_execute_transactions()`, but specialized for our
// special kind of transactions, that are known to fail and are only going to update the payer
// account.
fn load_and_execute_failed_transaction(
    bank: &Bank,
    batch: &TransactionBatch<impl TransactionWithMeta>,
    max_age: usize,
    timings: &mut ExecuteTimings,
    error_metrics: &mut TransactionErrorMetrics,
) -> LoadAndExecuteTransactionsOutput {
    let sanitized_txs = batch.sanitized_transactions();

    let balance_collector = Some(BalanceCollector::new_with_transaction_count(
        sanitized_txs.len(),
    ));

    let (check_results, check_us) = measure_us!(bank.check_transactions(
        sanitized_txs,
        batch.lock_results(),
        max_age,
        error_metrics,
    ));
    timings.saturating_add_in_place(ExecuteTimingType::CheckUs, check_us);

    let mut processed_transactions_count = 0;
    let mut processed_non_vote_transactions_count = 0;
    let mut signature_count = 0;

    let processing_results = izip!(sanitized_txs, check_results)
        .map(|(tx, check_result)| {
            let SVMTransactionExecutionAndFeeBudgetLimits {
                budget: compute_budget,
                loaded_accounts_data_size_limit,
                fee_details,
            } = check_result?.compute_budget_and_limits?;

            let tx = tx.as_sanitized_transaction();
            let message = tx.message();

            let fee_payer = message.fee_payer();

            let mut fee_payer_account = bank
                .accounts()
                .load_with_fixed_root(&bank.ancestors, fee_payer)
                .ok_or(TransactionError::AccountNotFound)
                .inspect_err(|_| error_metrics.account_not_found += 1)?
                .0;

            let fee = fee_details.total_fee();

            fee_payer_account.checked_sub_lamports(fee).map_err(|_| {
                error_metrics.insufficient_funds += 1;
                TransactionError::InsufficientFundsForFee
            })?;

            let loaded_transaction = LoadedTransaction::new_for_failed_transaction_hotpath(
                *fee_payer,
                fee_payer_account,
                fee_details,
                compute_budget,
                loaded_accounts_data_size_limit.get(),
            );
            let execution_details = TransactionExecutionDetails::new_for_failed_transaction_hotpath(
                TransactionError::InstructionError(
                    0,
                    InstructionError::ComputationalBudgetExceeded,
                ),
            );

            let executed_tx = ExecutedTransaction {
                loaded_transaction,
                execution_details,
                programs_modified_by_tx: HashMap::new(),
            };

            processed_transactions_count += 1;
            processed_non_vote_transactions_count += 1;
            signature_count += u64::from(message.header().num_required_signatures);

            error_metrics.instruction_error += 1;

            Ok(ProcessedTransaction::Executed(Box::new(executed_tx)))
        })
        .collect();

    let processed_counts = ProcessedTransactionCounts {
        processed_transactions_count,
        processed_non_vote_transactions_count,
        // All of the transactions are expected to fail process, or later, during the execution.
        processed_with_successful_result_count: 0,
        signature_count,
    };

    LoadAndExecuteTransactionsOutput {
        processing_results,
        processed_counts,
        balance_collector,
    }
}

#[cfg(test)]
mod tests {
    use {
        crate::banking_stage::{
            committer::Committer,
            consumer::{Consumer, ProcessTransactionBatchOutput},
            qos_service::QosService,
            scheduler_messages::MaxAge,
        },
        agave_feature_set::FeatureSet,
        crossbeam_channel::{unbounded, Receiver},
        solana_account::Account,
        solana_cluster_type::ClusterType,
        solana_compute_budget_interface::ComputeBudgetInstruction,
        solana_cost_model::cost_model::CostModel,
        solana_fee_calculator::FeeRateGovernor,
        solana_genesis_config::GenesisConfig,
        solana_hash::Hash,
        solana_keypair::Keypair,
        solana_ledger::{
            blockstore::Blockstore, blockstore_processor::TransactionStatusSender,
            genesis_utils::bootstrap_validator_stake_lamports, get_tmp_ledger_path_auto_delete,
            leader_schedule_cache::LeaderScheduleCache,
        },
        solana_poh::{
            poh_recorder::{PohRecorder, WorkingBankEntry},
            record_channels::{record_channels, RecordReceiver},
            transaction_recorder::TransactionRecorder,
        },
        solana_poh_config::PohConfig,
        solana_pubkey::Pubkey,
        solana_rent::Rent,
        solana_rpc::transaction_status_service::TransactionStatusService,
        solana_runtime::{
            bank::Bank, bank_forks::BankForks, genesis_utils::create_genesis_config_with_leader_ex,
            prioritization_fee_cache::PrioritizationFeeCache,
        },
        solana_runtime_transaction::runtime_transaction::RuntimeTransaction,
        solana_sdk_ids::system_program,
        solana_seed_derivable::SeedDerivable as _,
        solana_signer::Signer,
        solana_system_interface::instruction as system_instruction,
        solana_transaction::{sanitized::SanitizedTransaction, Transaction},
        std::{
            iter,
            sync::{
                atomic::{self, AtomicBool, AtomicU64},
                Arc, RwLock,
            },
        },
        tempfile::TempDir,
        test_case::test_case,
    };

    /// A helper that constructs a `GenesisConfig` and allows a convenient addition of extra
    /// arguments in there.
    struct SimpleSetupConfig {
        genesis_config: GenesisConfig,
        mint_keypair: Keypair,
    }

    impl SimpleSetupConfig {
        fn new(mint_lamports: u64) -> Self {
            let bootstrap_keypair = Keypair::from_seed(&(0..32).collect::<Vec<_>>()).unwrap();
            let bootstrap_lamports = 1000;
            let bootstrap_stake_lamports = bootstrap_validator_stake_lamports() + 100_000;
            let bootstrap_voting_keypair =
                Keypair::from_seed(&(32..64).collect::<Vec<_>>()).unwrap();

            let mint_keypair = Keypair::from_seed(&(5..37).collect::<Vec<_>>()).unwrap();

            // `FeeRateGovernor` should be going away, but if I use the `default()` value for it, I
            // see the signature fees drop to 0 in the `load_and_execute_failed_transaction()`.
            let fee_rate_governor = {
                let mut governor = FeeRateGovernor::default();
                // Pretend we are under load, such that the `lamports_per_signature` is now
                // non-zero.
                governor.lamports_per_signature = governor.target_lamports_per_signature;
                governor
            };
            let rent = Rent::default();

            let genesis_config = create_genesis_config_with_leader_ex(
                mint_lamports,
                &mint_keypair.pubkey(),
                &bootstrap_keypair.pubkey(),
                &bootstrap_voting_keypair.pubkey(),
                &Pubkey::new_unique(),
                None,
                bootstrap_stake_lamports,
                bootstrap_lamports,
                fee_rate_governor,
                rent,
                ClusterType::Development,
                vec![],
            );

            Self {
                genesis_config,
                mint_keypair,
            }
        }

        fn construct(self) -> SimpleSetup {
            SimpleSetup::construct(self)
        }

        /// Adds an empty account with the specified balance to the genesis.  Account keypair is
        /// returned.
        fn add_empty_account(&mut self, balance: u64) -> Keypair {
            let keypair = Keypair::new();
            let address = keypair.pubkey();

            let account = Account {
                lamports: balance,
                data: vec![],
                owner: system_program::id(),
                executable: false,
                rent_epoch: 0,
            };
            self.genesis_config.accounts.insert(address, account);

            keypair
        }

        fn add_n_empty_accounts(&mut self, n: u64, balance: u64) -> Vec<Keypair> {
            (0..n).map(|_| self.add_empty_account(balance)).collect()
        }
    }

    /// Components of the `SimpleSetup` that the test code wants to interact with directly.
    ///
    /// This is a return type for the `SimpleSetup::get_controls()` and it removes some of the
    /// "noise" from the test body.
    struct SimpleSetupControls<'setup> {
        pub bank: Arc<Bank>,
        pub mint_keypair: Keypair,
        pub consumer: &'setup Consumer,
    }

    /// Creates all the objects necessary for a failed transaction hotpath test, ties them together
    /// and returns them for use in the test.  Uses an instance of [`SimpleSetupConfig`] as a
    /// starting point.
    //
    // A number of fields are marked with `#[allow(unused)]` all of them are holding pieces of the
    // setup that we want to keep alive until the end of the test.  Clippy does not understand that.
    struct SimpleSetup {
        pub bank: Arc<Bank>,
        pub mint_keypair: Keypair,
        pub consumer: Consumer,

        #[allow(unused)]
        pub ledger_path: TempDir,
        #[allow(unused)]
        pub blockstore: Arc<Blockstore>,
        #[allow(unused)]
        pub bank_forks: Arc<RwLock<BankForks>>,
        #[allow(unused)]
        pub record_receiver: RecordReceiver,
        #[allow(unused)]
        pub entry_receiver: Receiver<WorkingBankEntry>,
        #[allow(unused)]
        pub poh_recorder: Arc<RwLock<PohRecorder>>,
        #[allow(unused)]
        pub transaction_status_service: TransactionStatusService,
        #[allow(unused)]
        pub transaction_status_service_exit_flag: Arc<AtomicBool>,
    }

    impl SimpleSetup {
        fn construct(
            SimpleSetupConfig {
                genesis_config,
                mint_keypair,
            }: SimpleSetupConfig,
        ) -> Self {
            let (bank, bank_forks) = Bank::new_no_wallclock_throttle_for_tests(&genesis_config);

            let ledger_path = get_tmp_ledger_path_auto_delete!();
            let blockstore = Blockstore::open(ledger_path.path())
                .expect("Expected to be able to open database ledger");
            let blockstore = Arc::new(blockstore);

            let (mut poh_recorder, entry_receiver) = PohRecorder::new(
                bank.tick_height(),
                bank.last_blockhash(),
                bank.clone(),
                Some((4, 4)),
                bank.ticks_per_slot(),
                blockstore.clone(),
                &Arc::new(LeaderScheduleCache::new_from_bank(&bank)),
                &PohConfig::default(),
                Arc::default(),
            );
            poh_recorder.set_bank_for_test(bank.clone());

            let (record_sender, mut record_receiver) = record_channels(false);
            let transaction_recorder = TransactionRecorder::new(record_sender);
            record_receiver.restart(bank.slot());

            let poh_recorder = Arc::new(RwLock::new(poh_recorder));

            let (transaction_status_sender, transaction_status_receiver) = unbounded();
            let transaction_status_service_exit_flag = Arc::new(AtomicBool::new(false));
            let transaction_status_service = TransactionStatusService::new(
                transaction_status_receiver,
                Arc::new(AtomicU64::default()),
                true,
                None,
                blockstore.clone(),
                false,
                None,
                transaction_status_service_exit_flag.clone(),
            );

            let (replay_vote_sender, _replay_vote_receiver) = unbounded();
            let committer = Committer::new(
                Some(TransactionStatusSender {
                    sender: transaction_status_sender,
                    dependency_tracker: None,
                }),
                replay_vote_sender,
                Arc::new(PrioritizationFeeCache::new(0u64)),
            );

            let qos_service = QosService::new(918);

            let consumer = Consumer::new(committer, transaction_recorder, qos_service, None);

            Self {
                bank,
                mint_keypair,
                consumer,
                ledger_path,
                blockstore,
                bank_forks,
                record_receiver,
                entry_receiver,
                poh_recorder,
                transaction_status_service,
                transaction_status_service_exit_flag,
            }
        }

        pub fn get_controls(&self) -> SimpleSetupControls {
            let Self {
                bank,
                mint_keypair,
                consumer,
                ..
            } = self;
            let bank = bank.clone();
            let mint_keypair = mint_keypair.insecure_clone();

            SimpleSetupControls {
                bank,
                mint_keypair,
                consumer,
            }
        }

        /// Starts shutdown for different components of the setup, and waits for them to finish the
        /// process.
        pub fn shutdown(self) {
            let Self {
                consumer,
                poh_recorder,
                transaction_status_service,
                transaction_status_service_exit_flag,
                ..
            } = self;

            drop(consumer);

            transaction_status_service
                .quiesce_and_join_for_tests(transaction_status_service_exit_flag);

            poh_recorder
                .read()
                .unwrap()
                .is_exited
                .store(true, atomic::Ordering::Relaxed);
        }
    }

    fn transfer_tx_with_budget(
        from_keypair: &Keypair,
        from_pubkey: &Pubkey,
        to_pubkey: &Pubkey,
        amount: u64,
        blockhash: Hash,
    ) -> RuntimeTransaction<SanitizedTransaction> {
        let tx = Transaction::new_signed_with_payer(
            &[
                ComputeBudgetInstruction::set_compute_unit_limit(25_000),
                system_instruction::transfer(from_pubkey, to_pubkey, amount),
            ],
            Some(from_pubkey),
            &[&from_keypair],
            blockhash,
        );
        RuntimeTransaction::from_transaction_for_tests(tx)
    }

    // A transaction that holds a single transfer.  Run in both "normal" and failed transaction
    // hotpath modes.
    //
    // The normal mode execution is a verification that the setup is actually working in the first
    // place.
    //
    // Failed transaction hotpath is expected to update just the payer balance, and not perform the
    // actual transfer.
    #[test_case(true)]
    #[test_case(false)]
    fn one_transfer_transaction(use_failed_transaction_hotpath: bool) {
        let mut setup_config = SimpleSetupConfig::new(100_000);
        let actor1 = setup_config.add_empty_account(7_000);

        let setup = setup_config.construct();
        let SimpleSetupControls {
            bank,
            mint_keypair,
            consumer,
        } = setup.get_controls();

        let actor1_pubkey = actor1.pubkey();
        let mint_pubkey = mint_keypair.pubkey();

        let mint_balance_before = bank.get_balance(&mint_pubkey);
        let actor1_balance_before = bank.get_balance(&actor1_pubkey);

        let tx = transfer_tx_with_budget(
            &mint_keypair,
            &mint_pubkey,
            &actor1_pubkey,
            1_000,
            bank.last_blockhash(),
        );

        // This is expected to call the
        // `failed_transaction_hotpath::process_and_record_aged_transactions()` internally.
        consumer.process_and_record_aged_transactions(
            &bank,
            use_failed_transaction_hotpath,
            &[tx],
            &[MaxAge::MAX; 1],
        );

        setup.shutdown();

        let mint_balance_after = bank.get_balance(&mint_pubkey);
        let actor1_balance_after = bank.get_balance(&actor1_pubkey);

        assert_eq!(
            mint_balance_after,
            mint_balance_before.saturating_sub(bank.fee_structure().lamports_per_signature),
        );
        assert_eq!(actor1_balance_before, actor1_balance_after);
    }

    // This test is very similar to `one_transfer_transaction`, but uses two signature in the
    // transaction, so we expect a different different payment compared to the
    // `one_transfer_transaction`.
    #[test]
    fn two_transfers_transaction() {
        let mut setup_config = SimpleSetupConfig::new(100_000);
        let actor1 = setup_config.add_empty_account(8_000);
        let actor2 = setup_config.add_empty_account(9_000);

        let setup = setup_config.construct();
        let SimpleSetupControls {
            bank,
            mint_keypair,
            consumer,
        } = setup.get_controls();

        let actor1_pubkey = actor1.pubkey();
        let actor2_pubkey = actor2.pubkey();
        let mint_pubkey = mint_keypair.pubkey();

        let mint_balance_before = bank.get_balance(&mint_pubkey);
        let actor1_balance_before = bank.get_balance(&actor1_pubkey);
        let actor2_balance_before = bank.get_balance(&actor2_pubkey);

        let tx = Transaction::new_signed_with_payer(
            &[
                ComputeBudgetInstruction::set_compute_unit_limit(25_000),
                system_instruction::transfer(&mint_pubkey, &actor1_pubkey, 5_000),
                system_instruction::transfer(&actor1_pubkey, &actor2_pubkey, 7_500),
            ],
            Some(&mint_pubkey),
            &[&mint_keypair, &actor1],
            bank.last_blockhash(),
        );
        let tx = RuntimeTransaction::from_transaction_for_tests(tx);
        let tx_required_signature_count = tx.message().header().num_required_signatures;

        let use_failed_transaction_hotpath = true;
        // This is expected to call the
        // `failed_transaction_hotpath::process_and_record_aged_transactions()` internally.
        consumer.process_and_record_aged_transactions(
            &bank,
            use_failed_transaction_hotpath,
            &[tx],
            &[MaxAge::MAX; 1],
        );

        setup.shutdown();

        let mint_balance_after = bank.get_balance(&mint_pubkey);
        let actor1_balance_after = bank.get_balance(&actor1_pubkey);
        let actor2_balance_after = bank.get_balance(&actor2_pubkey);

        let expected_required_signature_count = 2;
        assert_eq!(
            expected_required_signature_count,
            tx_required_signature_count
        );
        assert_eq!(
            mint_balance_after,
            mint_balance_before.saturating_sub(
                u64::from(expected_required_signature_count)
                    * bank.fee_structure().lamports_per_signature
            ),
        );
        assert_eq!(actor1_balance_before, actor1_balance_after);
        assert_eq!(actor2_balance_before, actor2_balance_after);
    }

    // This test verifies that the failed transaction hotpath is correctly overestimating the
    // transaction costs, and would not produce a block that would be invalid when actually
    // replayed.
    #[test]
    fn fully_packed_block() {
        let tx_count_expected_to_fit = 10;
        let tx_count_expected_to_be_throttled = 5;
        let tx_count = tx_count_expected_to_fit + tx_count_expected_to_be_throttled;

        // Failed transaction hostpath is only estimating the transaction costs, so it should be
        // using this value as the cost, when determining if the block is full.
        let tx_cost_estimate = {
            let actor1 = Keypair::new();
            let tx = transfer_tx_with_budget(
                &actor1,
                &actor1.pubkey(),
                &Pubkey::default(),
                1_000,
                Hash::default(),
            );
            CostModel::calculate_cost(&tx, &FeatureSet::all_enabled()).sum()
        };

        // Set the block cost limits to fit only the `tx_count_expected_to_fit` transactions, if
        // their cost is only estimated.
        fn set_bank_cost_limits(bank: &Bank, tx_cost_estimate: u64, tx_count_expected_to_fit: u64) {
            let mut cost_tracker = bank.write_cost_tracker().unwrap();
            let block_cost_limit = tx_cost_estimate * tx_count_expected_to_fit;
            // While normally the `account_cost_limit` and the `vote_cost_limit` are lower than the
            // `block_cost_limit`, for the purposes of this test it is OK for them to be equal.
            cost_tracker.set_limits(block_cost_limit, block_cost_limit, block_cost_limit);
        }

        // Runs `tx_count` transactions, and returns execution stats and the bank.
        let run_one_block =
            |use_failed_transaction_hotpath: bool| -> (ProcessTransactionBatchOutput, Arc<Bank>) {
                let mut setup_config = SimpleSetupConfig::new(100_000);
                // Make sure the accounts in different transactions do not overlap.
                let actors = setup_config.add_n_empty_accounts(2 * tx_count, 35_000);
                let actor_pubkeys = actors
                    .iter()
                    .map(|actor| actor.pubkey())
                    .collect::<Vec<_>>();

                let setup = setup_config.construct();
                let SimpleSetupControls { bank, consumer, .. } = setup.get_controls();

                set_bank_cost_limits(&bank, tx_cost_estimate, tx_count_expected_to_fit);

                let txs = (0..usize::try_from(tx_count).unwrap())
                    .map(|i| {
                        transfer_tx_with_budget(
                            &actors[2 * i],
                            &actor_pubkeys[2 * i],
                            &actor_pubkeys[2 * i + 1],
                            1_000,
                            bank.last_blockhash(),
                        )
                    })
                    .collect::<Vec<_>>();

                let processing_result = consumer.process_and_record_aged_transactions(
                    &bank,
                    use_failed_transaction_hotpath,
                    &txs,
                    &iter::repeat_n(MaxAge::MAX, txs.len()).collect::<Vec<_>>(),
                );

                setup.shutdown();

                (processing_result, bank)
            };

        // In the failed transaction hotpath case we expect the bank to exhaust the block cost.
        let (processing_result, hotpath_case_bank) =
            run_one_block(/* use_failed_transaction_hotpath: */ true);

        assert_eq!(
            processing_result
                .execute_and_commit_transactions_output
                .transaction_counts
                .processed_count,
            tx_count_expected_to_fit,
        );
        assert_eq!(
            tx_count_expected_to_be_throttled,
            processing_result.cost_model_throttled_transactions_count,
        );

        let hotpath_block_cost = hotpath_case_bank.read_cost_tracker().unwrap().block_cost();
        assert_eq!(
            hotpath_block_cost,
            tx_cost_estimate * tx_count_expected_to_fit
        );

        // In the normal case, due to the transaction cost being recalculated based on the actual
        // execution price, expect the bank to have a much lower block cost accumulated from the
        // same set of transactions.
        //
        // QosService will still block transaction execution based on the cost estimate, rather than
        // the execution cost.
        let (processing_result, normal_case_bank) =
            run_one_block(/* use_failed_transaction_hotpath: */ false);

        assert_eq!(
            processing_result
                .execute_and_commit_transactions_output
                .transaction_counts
                .processed_count,
            tx_count_expected_to_fit,
        );
        assert_eq!(
            tx_count_expected_to_be_throttled,
            processing_result.cost_model_throttled_transactions_count,
        );

        let normal_block_cost = normal_case_bank.read_cost_tracker().unwrap().block_cost();
        assert!(
            normal_block_cost + tx_cost_estimate < hotpath_block_cost,
            "While transactions are added to the bank based on the estimates, we expect the \
             failed transaction hot path to use estimates for the actual cost as well.\nAs a \
             result, in the normal processing case we should still have enough space to add at \
             least one more transaction, compared to the hotpath case.\nFailed transaction \
             hotpath bank cost for {tx_count_expected_to_fit} txs: {hotpath_block_cost}\nNormal \
             flow bank cost for {tx_count_expected_to_fit} txs: {normal_block_cost}\nEstimate \
             transaction cost: {tx_cost_estimate}
            "
        );
    }
}
